name: Build
on: [push]
env:
  TOOLCHAIN_IMAGE: ${{ secrets.DOCKER_ORGANIZATION }}/toolchain
  TOOLCHAIN_TAG: 0.13.0
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          token: ${{ secrets.CI_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build yield tool
        run: cd linux/htif && make toolchain-exec CONTAINER_COMMAND="/usr/bin/make yield.toolchain"

      - name: Build ioctl-echo-loop tool
        run: cd linux/rollup/ioctl-echo-loop && make toolchain-exec CONTAINER_COMMAND="/usr/bin/make ioctl-echo-loop.toolchain"

      - name: Build rollup tool
        run: cd linux/rollup/rollup && make toolchain-exec CONTAINER_COMMAND="/usr/bin/make rollup.toolchain"

      - name: Build rollup http server
        run: cd linux/rollup/http/rollup-http-server && ./build.sh

      - name: Build echo dapp
        run: cd linux/rollup/http/echo-dapp && ./build.sh

      - name: Test rollup-http-server and echo-dapp client
        run: |
          cd linux/rollup/http/rollup-http-server
          USE_ROLLUP_BINDINGS_MOCK=1 cargo test -- --show-output --test-threads=1
