name: Build
on: [push]
env:
  TOOLCHAIN_IMAGE: ${{ secrets.DOCKER_ORGANIZATION }}/toolchain
  TOOLCHAIN_TAG: 0.7.0
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          token: ${{ secrets.CI_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build dehash tool
        run: cd linux/dehash && make toolchain-exec CONTAINER_COMMAND="/usr/bin/make dehash.toolchain"

      - name: Build yield tool
        run: cd linux/htif && make toolchain-exec CONTAINER_COMMAND="/usr/bin/make yield.toolchain"
