name: Build
on: [push]
env:
  TOOLCHAIN_IMAGE: ${{ secrets.DOCKER_ORGANIZATION }}/toolchain
  TOOLCHAIN_TAG: 0.14.0
jobs:
  tools:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          token: ${{ secrets.CI_TOKEN }}
          fetch-depth: 0 # fetch tags

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Export makefile variables
        run: make env >> $GITHUB_ENV

      - name: Download [linux-sources]
        run: >
          gh release download -D dep/ -R ${{ github.repository_owner }}/linux v${{ env.LINUX_SOURCES_VERSION }} --archive=tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.CI_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Build ${{ env.MACHINE_EMULATOR_TOOLS_TAR_GZ }}
        run: make ${{ env.MACHINE_EMULATOR_TOOLS_TAR_GZ }}

      - name: Upload ${{ env.MACHINE_EMULATOR_TOOLS_TAR_GZ }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.MACHINE_EMULATOR_TOOLS_TAR_GZ }}
          path: ${{ env.MACHINE_EMULATOR_TOOLS_TAR_GZ }}

      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          prerelease: true
          files: |
            ${{ env.MACHINE_EMULATOR_TOOLS_TAR_GZ }}

  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          token: ${{ secrets.CI_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build yield tool
        run: cd linux/htif && make toolchain-exec CONTAINER_COMMAND="/usr/bin/make yield.toolchain"

      - name: Build ioctl-echo-loop tool
        run: cd linux/rollup/ioctl-echo-loop && make toolchain-exec CONTAINER_COMMAND="/usr/bin/make ioctl-echo-loop.toolchain"

      - name: Build rollup tool
        run: cd linux/rollup/rollup && make toolchain-exec CONTAINER_COMMAND="/usr/bin/make rollup.toolchain"

      - name: Build rollup http server
        run: cd linux/rollup/http/rollup-http-server && ./build.sh

      - name: Build echo dapp
        run: cd linux/rollup/http/echo-dapp && ./build.sh

      - name: Test rollup-http-server and echo-dapp client
        run: |
          cd linux/rollup/http/rollup-http-server
          USE_ROLLUP_BINDINGS_MOCK=1 cargo test -- --show-output --test-threads=1
