name: Build
on: [push]
env:
  TOOLCHAIN_IMAGE: ${{ github.repository_owner }}/toolchain
  TOOLCHAIN_TAG: 0.16.0
jobs:
  tools:
    runs-on: ubuntu-22.04
    steps:
      - name: Install libarchive-tools
        run: |
          export DEBIAN_FRONTEND=noninteractive
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends build-essential autoconf automake libarchive-dev libarchive-tools

      # Building from source cause the provided debian package is for Debian Bookworm
      - name: Download, build and install xgenext2fs
        run: |
          wget https://github.com/cartesi/genext2fs/archive/refs/tags/v1.5.3.tar.gz
          echo "af62ec69916ffc15fa5921b19630c9935e69a0d8b1bf529d7f26cefdc23a5120  v1.5.3.tar.gz" | sha256sum -c -
          tar -xzf v1.5.3.tar.gz
          cd genext2fs-1.5.3
          ./autogen.sh
          ./configure
          make
          sudo make install
          rm -rf genext2fs-1.5.3 v1.5.3.tar.gz

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Export makefile variables
        run: make env >> $GITHUB_ENV

      - name: Create debian package control file
        run: make control

      - name: Buildx setup
        uses: docker/setup-buildx-action@v2

      - name: Build [${{ env.TOOLS_DEB }}]
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: .
          builder: ${{ steps.buildx.outputs.name }}
          tags: ${{ env.TOOLS_IMAGE }}
          push: false
          load: true
          build-args: |
            TOOLS_DEB=${{ env.TOOLS_DEB }}
            LINUX_SOURCES_VERSION=${{ env.LINUX_SOURCES_VERSION }}
            LINUX_SOURCES_URLPATH=${{ env.LINUX_SOURCES_URLPATH }}
          cache-from: type=gha,scope=regular,mode=max
          cache-to: type=gha,scope=regular

      - name: Retrieve artifacts
        run: make copy

      - name: Build rootfs
        run: make fs

      - name: Upload [${{ env.TOOLS_DEB }}]
        uses: actions/upload-artifact@v3
        with:
          path: ${{ env.TOOLS_DEB }}

      - name: Upload [${{ env.TOOLS_ROOTFS }}]
        uses: actions/upload-artifact@v3
        with:
          path: ${{ env.TOOLS_ROOTFS }}

      - name: Checksum artifacts
        run: |
          sha512sum ${{ env.TOOLS_DEB }} > ${{ env.TOOLS_DEB }}.sha512
          sha512sum ${{ env.TOOLS_ROOTFS }} > ${{ env.TOOLS_ROOTFS }}.sha512

      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          prerelease: true
          files: |
            ${{ env.TOOLS_DEB }}
            ${{ env.TOOLS_DEB }}.sha512
            ${{ env.TOOLS_ROOTFS }}
            ${{ env.TOOLS_ROOTFS }}.sha512

  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build yield tool
        run: cd linux/htif && make toolchain-exec CONTAINER_COMMAND="/usr/bin/make yield.toolchain"

      - name: Build ioctl-echo-loop tool
        run: cd linux/rollup/ioctl-echo-loop && make toolchain-exec CONTAINER_COMMAND="/usr/bin/make ioctl-echo-loop.toolchain"

      - name: Build rollup tool
        run: cd linux/rollup/rollup && make toolchain-exec CONTAINER_COMMAND="/usr/bin/make rollup.toolchain"

      - name: Build rollup http server
        run: cd linux/rollup/http/rollup-http-server && ./build.sh

      - name: Build echo dapp
        run: cd linux/rollup/http/echo-dapp && ./build.sh

      - name: Test rollup-http-server and echo-dapp client
        run: |
          cd linux/rollup/http/rollup-http-server
          USE_ROLLUP_BINDINGS_MOCK=1 cargo test -- --show-output --test-threads=1
